### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by mwolff44** [aschenmaker/fiber-health-check#2]
Hi,
sorry for my simple question, but i do not understand how to use it. How to link the url with the middleware ?
I try "/" with the appropriate header without success.
I am new to fiber.
Regards

**Comment by zhujunjie-c** [comment]
When using, add an x-health-check to the header and set its value to 1（in your request）
```
    app := fiber.New()
    app.Use(healthcheck.New())
    app.Get("/", func(c *fiber.Ctx) error {
	  return c.Status(http.StatusNoContent).SendString("test default")
    })
    app.Listen(":3000")`;
```
	


header like this

`
header:{
      X-Health-Check:1
}
`

**Comment by mwolff44** [comment]
Hi,
Thanks for your quick reply.
Regards
